### ISSUE TITLE
Increasing the Ring buffer size to support Modbus protocol

### ISSUE THREAD

**Issue by dhineshkumarmcci** [mcci-catena/ArduinoCore-samd#26]
As per the spec of Modbus protocol, it is possible to read 125 registers at once. With the current version of SAMD BSP, BAD CRC has been thrown on reading more than 79 registers (163 bytes). This is because of the limit in Serial buffer size as 164. 

To read more than 79 registers (up to 125), we have to increase the serial buffer size `SERIAL_BUFFER_SIZE` to **256** in **RingBuffer.h**. The coding part to be updated is below:

https://github.com/mcci-catena/ArduinoCore-samd/blob/31c3b29e80a5ee48974e5817e3d467e1ac704819/cores/arduino/RingBuffer.h#L28

On increasing the serial buffer size to 256, Catena 4470 was able to read 125 registers.

**Comment by terrillmoore** [comment]
Please submit a pull request, thanks.
